version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - cd web
      - npm install --production
  build:
    commands:
      - npm run build:prod
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id ENJ1N3LVDLPPB --paths "/*"

artifacts:
  files: 
    - '**/*'
  base-directory: 'web/build'