version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - cd api
      - npm install -g typescript
      - npm install
  build:
    commands:
      - tsc

artifacts:
  files: 
    - '**/*'
  base-directory: 'api/build'
