version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - n 18
      - cd api
      - npm install -g typescript
      - npm install
  build:
    commands:
      - tsc

artifacts:
  files:
    - api/build/package.json
    - api/build/package-lock.json
    - 'api/build/**/*'
